My First Microverse project
Stanleeeeee/Hello-microverse1 pull request #1
Opened 2022-03-16 14:13 UTC by Stanleeeeee

This is my HELLO MICROVERSE project to practice the basic setup of a project repository. In this project repository, I had to create :
 .gitignore file, 
Readme.md, 
index.html, 
style.css 
added a linter file.

Please Kindly review my work.

2022-03-16 14:41 UTC, ShadyShawkat requested changes
## Hi @Stanleeeeee, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️

- [x] Please make sure to give your pull request a descriptive title. This will make it more professional. you can do so by clicking the "Edit" button in the top right of the page.
- [ ]  Kindly make sure to have a meaningful description in your pull request summarizing the features you implemented in it. You can edit this section by clicking the 3-dot icon in the top right side of this section and clicking "Edit".
- [ ] _Check the comments under the review for the rest of required changes._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-16 14:41 UTC, ShadyShawkat commented on .github/linters.yml
> +        run: npx stylelint "**/*.{css,scss}"
- [ ] Please make sure to set up the linters correctly. Currently your linters have the path `.github/linters.yml` which isn't the right path, the ccorrect path should be `.github/workflows/linters.yml`. Also, please be sure that the linters run correctly and pass with green checkmarks ✔️.

2022-03-16 14:41 UTC, ShadyShawkat commented on README.md
> +- Twitter: [@twitterhandle](https://twitter.com/Stanmega89)
- [x] Kindly write your name instead of "Author1".
- [x] Please use the following syntax which makes use of your handlers instead of writing "@githubhandle".
```
GitHub: [@stanleeeeee](https://github.com/stanleeeeee)
```

2022-03-16 14:41 UTC, ShadyShawkat commented on README.md
>  ### Prerequisites
- [ ] kindly correct the info inside the `Getting Started` section by adding information about how to clone and run your project.

2022-03-17 14:26 UTC, Stanleeeeee reviewed
Summary of the changes
Edited Readme file
Renamed my linters pathway

2022-03-17 14:53 UTC, BenMukebo approved these changes
## Hi *** @Stanleeeeee , *** 👋 

# STATUS: Approved  🎉 
Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 

<img src="https://media1.giphy.com/media/26u4lOMA8JKSnL9Uk/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-17 17:10 UTC, merged